const iconw = {
    "iconsDN": [
        {
            "Clear": './icon/moon.svg',
            "Cloudy": './icon/moonC.svg',
            "Partly Cloudy": './icon/moonC.svg',
            "Overcast": './icon/moonC.svg',
            "Mist": './icon/mist.svg',
            "Patchy rain nearby": './icon/Nrain.svg',
            "Patchy snow nearby": './icon/snow.svg',
            "Patchy sleet nearby": './icon/Nrain.svg',
            "Patchy freezing drizzle nearby": './icon/cold.svg',
            "Thundery outbreaks in nearby": './icon/storm.svg',
            "Blowing snow": './icon/snow.svg',
            "Blizzard": './icon/snow.svg',
            "Fog": './icon/mist.svg',
            "Freezing fog": './icon/mist.svg',
            "Patchy light drizzle": './icon/Nrain.svg',
            "Light drizzle": './icon/Nrain.svg',
            "Freezing drizzle": './icon/Nrain.svg',
            "Heavy freezing drizzle": './icon/Nrain.svg',
            "Patchy light rain": './icon/Nrain.svg',
            "Light rain": './icon/Nrain.svg',
            "Moderate rain at times": './icon/Nrain.svg',
            "Moderate rain": './icon/Nrain.svg',
            "Heavy rain at times": './icon/Nrain.svg',
            "Heavy rain": './icon/Nrain.svg',
            "Light freezing rain": './icon/Nrain.svg',
            "Moderate or heavy freezing rain": './icon/Nrain.svg',
            "Light sleet": './icon/snow.svg',
            "Moderate or heavy sleet": './icon/snow.svg',
            "Patchy light snow": './icon/snow.svg',
            "Light snow": './icon/snow.svg',
            "Patchy moderate snow": './icon/snow.svg',
            "Moderate snow": './icon/snow.svg',
            "Patchy heavy snow": './icon/snow.svg',
            "Heavy snow": './icon/snow.svg',
            "Ice pellets": './icon/snow.svg', 
            "Light rain shower": './icon/Nrain.svg',
            "Moderate or heavy rain shower": './icon/Nrain.svg',
            "Torrential rain shower": './icon/Nrain.svg',
            "Light sleet showers": './icon/snow.svg',
            "Moderate or heavy sleet showers": './icon/snow.svg',
            "Light snow showers": './icon/snow.svg',
            "Moderate or heavy snow showers": './icon/snow.svg',
            "Light showers of ice pellets": './icon/snow.svg',
            "Moderate or heavy showers of ice pellets": './icon/snow.svg',
            "Patchy light rain in area with thunder": './icon/Nrain.svg',
            "Moderate or heavy rain in area with thunder": './icon/Nrain.svg',
            "Patchy light snow in area with thunder": './icon/snow.svg',
            "Moderate or heavy snow in area with thunder": './icon/snow.svg'
        },

        {
        "Sunny":  './icon/sun.svg',
        "Clear": './icon/sun.svg',
        "Cloudy": './icon/cloud.svg',
        "Partly Cloudy": './icon/cloud.svg',
        "Overcast": './icon/cloud.svg',
        "Mist": './icon/mist.svg',
        "Patchy rain nearby": './icon/rain.svg',
        "Patchy snow nearby": './icon/snow.svg',
        "Patchy sleet nearby": './icon/rain.svg',
        "Patchy freezing drizzle nearby": './icon/cold.svg',
        "Thundery outbreaks in nearby": './icon/storm.svg',
        "Blowing snow": './icon/snow.svg',
        "Blizzard": './icon/snow.svg',
        "Fog": './icon/mist.svg',
        "Freezing fog": './icon/mist.svg',
        "Patchy light drizzle": './icon/rain.svg',
        "Light drizzle": './icon/rainSun.svg',
        "Freezing drizzle": './icon/rainSun.svg',
        "Heavy freezing drizzle": './icon/rainSun.svg',
        "Patchy light rain": './icon/rain.svg',
        "Light rain": './icon/rain.svg',
        "Moderate rain at times": './icon/rain.svg',
        "Moderate rain": './icon/rain.svg',
        "Heavy rain at times": './icon/rainSun.svg',
        "Heavy rain": './icon/rainSun.svg',
        "Light freezing rain": './icon/rain.svg',
        "Moderate or heavy freezing rain": './icon/rainSun.svg',
        "Light sleet": './icon/snow.svg',
        "Moderate or heavy sleet": './icon/snow.svg',
        "Patchy light snow": './icon/snow.svg',
        "Light snow": './icon/snow.svg',
        "Patchy moderate snow": './icon/snow.svg',
        "Moderate snow": './icon/snow.svg',
        "Patchy heavy snow": './icon/snow.svg',
        "Heavy snow": './icon/snow.svg',
        "Ice pellets": './icon/snow.svg', 
        "Light rain shower": './icon/rain.svg',
        "Moderate or heavy rain shower": './icon/rainSun.svg',
        "Torrential rain shower": './icon/rainSun.svg',
        "Light sleet showers": './icon/snow.svg',
        "Moderate or heavy sleet showers": './icon/snow.svg',
        "Light snow showers": './icon/snow.svg',
        "Moderate or heavy snow showers": './icon/snow.svg',
        "Light showers of ice pellets": './icon/snow.svg',
        "Moderate or heavy showers of ice pellets": './icon/snow.svg',
        "Patchy light rain in area with thunder": './icon/rainSun.svg',
        "Moderate or heavy rain in area with thunder": './icon/rainSun.svg',
        "Patchy light snow in area with thunder": './icon/snow.svg',
        "Moderate or heavy snow in area with thunder": './icon/snow.svg'
        }]
}

export default iconw;