const iconw = {
    "iconsDN": [
        {
            "Clear": './public/icon/moon.svg',
            "Cloudy": './public/icon/moonC.svg',
            "Partly Cloudy": './public/icon/moonC.svg',
            "Overcast": './public/icon/moonC.svg',
            "Mist": './public/icon/mist.svg',
            "Patchy rain nearby": './public/icon/Nrain.svg',
            "Patchy snow nearby": './public/icon/snow.svg',
            "Patchy sleet nearby": './public/icon/Nrain.svg',
            "Patchy freezing drizzle nearby": './public/icon/cold.svg',
            "Thundery outbreaks in nearby": './public/icon/storm.svg',
            "Blowing snow": './public/icon/snow.svg',
            "Blizzard": './public/icon/snow.svg',
            "Fog": './public/icon/mist.svg',
            "Freezing fog": './public/icon/mist.svg',
            "Patchy light drizzle": './public/icon/Nrain.svg',
            "Light drizzle": './public/icon/Nrain.svg',
            "Freezing drizzle": './public/icon/Nrain.svg',
            "Heavy freezing drizzle": './public/icon/Nrain.svg',
            "Patchy light rain": './public/icon/Nrain.svg',
            "Light rain": './public/icon/Nrain.svg',
            "Moderate rain at times": './public/icon/Nrain.svg',
            "Moderate rain": './public/icon/Nrain.svg',
            "Heavy rain at times": './public/icon/Nrain.svg',
            "Heavy rain": './public/icon/Nrain.svg',
            "Light freezing rain": './public/icon/Nrain.svg',
            "Moderate or heavy freezing rain": './public/icon/Nrain.svg',
            "Light sleet": './public/icon/snow.svg',
            "Moderate or heavy sleet": './public/icon/snow.svg',
            "Patchy light snow": './public/icon/snow.svg',
            "Light snow": './public/icon/snow.svg',
            "Patchy moderate snow": './public/icon/snow.svg',
            "Moderate snow": './public/icon/snow.svg',
            "Patchy heavy snow": './public/icon/snow.svg',
            "Heavy snow": './public/icon/snow.svg',
            "Ice pellets": './public/icon/snow.svg', 
            "Light rain shower": './public/icon/Nrain.svg',
            "Moderate or heavy rain shower": './public/icon/Nrain.svg',
            "Torrential rain shower": './public/icon/Nrain.svg',
            "Light sleet showers": './public/icon/snow.svg',
            "Moderate or heavy sleet showers": './public/icon/snow.svg',
            "Light snow showers": './public/icon/snow.svg',
            "Moderate or heavy snow showers": './public/icon/snow.svg',
            "Light showers of ice pellets": './public/icon/snow.svg',
            "Moderate or heavy showers of ice pellets": './public/icon/snow.svg',
            "Patchy light rain in area with thunder": './public/icon/Nrain.svg',
            "Moderate or heavy rain in area with thunder": './public/icon/Nrain.svg',
            "Patchy light snow in area with thunder": './public/icon/snow.svg',
            "Moderate or heavy snow in area with thunder": './public/icon/snow.svg'
        },

        {
        "Sunny":  './public/icon/sun.svg',
        "Clear": './public/icon/sun.svg',
        "Cloudy": './public/icon/cloud.svg',
        "Partly Cloudy": './public/icon/cloud.svg',
        "Overcast": './public/icon/cloud.svg',
        "Mist": './public/icon/mist.svg',
        "Patchy rain nearby": './public/icon/rain.svg',
        "Patchy snow nearby": './public/icon/snow.svg',
        "Patchy sleet nearby": './public/icon/rain.svg',
        "Patchy freezing drizzle nearby": './public/icon/cold.svg',
        "Thundery outbreaks in nearby": './public/icon/storm.svg',
        "Blowing snow": './public/icon/snow.svg',
        "Blizzard": './public/icon/snow.svg',
        "Fog": './public/icon/mist.svg',
        "Freezing fog": './public/icon/mist.svg',
        "Patchy light drizzle": './public/icon/rain.svg',
        "Light drizzle": './public/icon/rainSun.svg',
        "Freezing drizzle": './public/icon/rainSun.svg',
        "Heavy freezing drizzle": './public/icon/rainSun.svg',
        "Patchy light rain": './public/icon/rain.svg',
        "Light rain": './public/icon/rain.svg',
        "Moderate rain at times": './public/icon/rain.svg',
        "Moderate rain": './public/icon/rain.svg',
        "Heavy rain at times": './public/icon/rainSun.svg',
        "Heavy rain": './public/icon/rainSun.svg',
        "Light freezing rain": './public/icon/rain.svg',
        "Moderate or heavy freezing rain": './public/icon/rainSun.svg',
        "Light sleet": './public/icon/snow.svg',
        "Moderate or heavy sleet": './public/icon/snow.svg',
        "Patchy light snow": './public/icon/snow.svg',
        "Light snow": './public/icon/snow.svg',
        "Patchy moderate snow": './public/icon/snow.svg',
        "Moderate snow": './public/icon/snow.svg',
        "Patchy heavy snow": './public/icon/snow.svg',
        "Heavy snow": './public/icon/snow.svg',
        "Ice pellets": './public/icon/snow.svg', 
        "Light rain shower": './public/icon/rain.svg',
        "Moderate or heavy rain shower": './public/icon/rainSun.svg',
        "Torrential rain shower": './public/icon/rainSun.svg',
        "Light sleet showers": './public/icon/snow.svg',
        "Moderate or heavy sleet showers": './public/icon/snow.svg',
        "Light snow showers": './public/icon/snow.svg',
        "Moderate or heavy snow showers": './public/icon/snow.svg',
        "Light showers of ice pellets": './public/icon/snow.svg',
        "Moderate or heavy showers of ice pellets": './public/icon/snow.svg',
        "Patchy light rain in area with thunder": './public/icon/rainSun.svg',
        "Moderate or heavy rain in area with thunder": './public/icon/rainSun.svg',
        "Patchy light snow in area with thunder": './public/icon/snow.svg',
        "Moderate or heavy snow in area with thunder": './public/icon/snow.svg'
        }]
}

export default iconw;